# vi:et:sw=2:ts=2
# Remember: do not use tabs in configuration files.
# See also: http://jekyllrb.com/docs/configuration/

encoding: utf-8
timezone: America/Sao_Paulo

# Site name (not used by Jekyll itself, only used in the template):
name: "Denilson Sá"
# In fact, any property from this _config.yml file can be referenced in a
# template using {{ site.foobar }}

# Used in RSS and Atom feeds.
production_url: "http://denilson.sa.nom.br/"

# site.url is filled in by GitHub Pages, but always point to HTTP.
# https://github.com/jekyll/github-metadata/issues/116
# Let's avoid using it and instead use site.baseurl.
baseurl: ''

# http://jekyllrb.com/docs/configuration/#frontmatter-defaults
defaults:
#  -
#    scope:
#      path: "" # an empty string here means all files in the project
#      type: "posts"  # Type can be pages, posts, drafts, or any collection.
#    values:
#      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      og_type: "article"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      og_type: "article"

#markdown: redcarpet
markdown: kramdown

# http://jekyllrb.com/docs/configuration/#markdown-options
# https://stackoverflow.com/questions/13464590/github-flavored-markdown-and-pygments-highlighting-in-jekyll
# https://stackoverflow.com/questions/373002/better-ruby-markdown-interpreter

# https://github.com/vmg/redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - strikethrough
    - tables
    - smart
    - with_toc_data
#    - superscript

# https://github.com/gettalong/kramdown
# http://kramdown.gettalong.org/syntax.html
# http://kramdown.gettalong.org/options.html
# http://kramdown.gettalong.org/parser/gfm.html
kramdown:
  # Still missing: autolink
  input: GFM
  # If true, inserts <br> for newlines in paragraphs.
  hard_wrap: false

  # "as_input", "numeric", "symbolic", "as_char"
  entity_output: "as_input"

  # "coderay" is the default, but it outputs different classes than rouge/pygments.
  # "rouge" seems a better choice.
  syntax_highlighter: "rouge"

  # syntax_highlighter_opts:
    # https://github.com/jneen/rouge#full-options
    # This is already the default:
    # line_numbers: false

  # Either "class" or "style".
  coderay_css: "class"
  # "table", "inline" or nil
  coderay_line_numbers: "table"

  # Requires "stringex" gem.
  # transliterated_header_ids: true

# Starting in Jekyll 2.0, absolute permalinks are the default.
relative_permalinks: false

# Inspired by: https://github.com/SLaks/SLaks.Blog/blob/gh-pages/_config.yml
permalink: /blog/:year-:month-:day/:title

# A single blank line (AKA a paragraph break, the default behavior).
#excerpt_separator: "\n\n"
# Two blank lines.
excerpt_separator: "\n\n\n"

# Produce an index for related posts.
#lsi: true
lsi: false

#paginate: 10

# Files to be excluded from the generated _site:
exclude:
  - /icons/originals/

include:
  - .well-known

# This will only be useful if the site is being served from a non-root
# directory. Also, post URLs alread contain the leading slash, which means
# baseurl should NOT contain a trailing slash.
#baseurl:

# Auto-regeneration can no longer be set from your configuration file(s). Use
# the --watch/-w command-line option instead.
#watch: true

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  # I may use: https://github.com/jekyll/jekyll-feed

# Further configuration:
# https://help.github.com/articles/redirects-on-github-pages
# https://help.github.com/articles/using-jekyll-with-pages
# https://help.github.com/articles/repository-metadata-on-github-pages
# https://help.github.com/articles/custom-404-pages
